name: Server Update

on:
  push:
    branches: [ master ]

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 
      - name: Deploy in Azure
        env:
            PRIVATE_KEY: ${{ secrets.AZAURE_PRIVATE_KEY  }}
            HOSTNAME : ${{ secrets.HOSTNAME  }}
            USER_NAME : ${{ secrets.USER_NAME  }}

        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
          
            #Now we have got the access of Azure Server and we will start the deploy .
            cd /var/www/dev.sachin.software/public_html/Romanized-Unicode-Typing-Nepali- &&
            sudo git checkout master &&
            sudo git fetch --all &&
            sudo git reset --hard origin/master &&
            sudo git pull origin master
          '
